[tool.poetry]
name = "bookwyrm"
version = "0.4.4"
description = "Social reading and reviewing, decentralized with ActivityPub"
authors = ["Mouse Reeve <mousereeve@riseup.net>"]

packages = [ { include = "bookwyrm"}, { include = "celerywyrm" } ]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "3.8.1"
bleach = "5.0.1"
celery = "5.2.2"
colorthief = "0.2.1"
Django = "3.2.14"
django-celery-beat = "2.2.1"
django-compressor = "2.4.1"
django-imagekit = "4.1.0"
django-model-utils = "4.0.0"
django-sass-processor = "1.0.1"
environs = "9.3.4"
flower = "1.0.0"
gunicorn = "20.0.4"
libsass = "0.21.0"
Markdown = "3.3.3"
packaging = "21.3"
Pillow = "^9.0.0"
psycopg2 = "2.8.4"
pycryptodome = "3.9.4"
python-dateutil = "2.8.1"
redis = "3.4.1"
requests = "2.22.0"
responses = "0.10.14"
pytz = "^2021.1"
boto3 = "^1.17"
django-storages = "^1.11"
django-redis = "5.2.0"
opentelemetry-api = "1.11.1"
opentelemetry-sdk = "1.11.1"
opentelemetry-exporter-otlp-proto-grpc = "1.11.1"
opentelemetry-instrumentation-django = "0.30b1"
opentelemetry-instrumentation-celery = "0.30b1"
protobuf = "^3.20.1"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1",  allow-prereleases = true}
coverage = "5.1"
pytest-django = "4.1.0"
pytest = "6.1.2"
pytest-cov = "2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
